// Phase 2E — tool universe barrel
export { getMarketSnapshot } from './marketSnapshot'
export { getMarketBreadth } from './breadth'
export { analyzeSectors } from './sectors'
export { getMarketMovers } from './movers'
export { getMacroContext } from './macro'
export { getTechnicalAnalysis } from './technicalAnalysis'
export { detectPatterns } from './patterns'
export { detectDivergences } from './divergences'
export { detectBreakouts } from './breakouts'
export { getConfluence } from './confluence'
export { getHistoricalValidation } from './historical'
export { compareInstruments } from './comparison'
export { createSearchWebTool, searchWeb } from './searchWeb'

export type { MarketSnapshotInput } from './marketSnapshot'
export type { MarketBreadthInput, MarketBreadthOutput } from './breadth'
export type { SectorsInput, SectorsOutput } from './sectors'
export type { MoversInput, MoversOutput, MoversCategory } from './movers'
export type { MacroContextInput, MacroContextOutput } from './macro'
export type { TechnicalAnalysisInput, TechnicalAnalysisOutput } from './technicalAnalysis'
export type { PatternsInput, PatternsOutput } from './patterns'
export type { DivergencesInput, DivergencesOutput } from './divergences'
export type { BreakoutsInput, BreakoutsOutput } from './breakouts'
export type { ConfluenceInput, ConfluenceOutput } from './confluence'
export type { HistoricalValidationInput, HistoricalValidationOutput } from './historical'
export type { ComparisonInput, ComparisonOutput } from './comparison'
export type { SearchWebInput, SearchWebToolOutput, SearchWebToolOptions } from './searchWeb'